project:
  type: website

website:
  title: "mve"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents: markdown/*/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



